// <auto-generated />
using System;
using AcademicManagmentSystem.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcademicManagmentSystem.API.Migrations
{
    [DbContext(typeof(AcademicManagmentSystemDbContext))]
    partial class AcademicManagmentSystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AcademicManagmentSystem.API.Data.Deo", b =>
                {
                    b.Property<int>("DeoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeoId"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PredmetId")
                        .HasColumnType("int");

                    b.HasKey("DeoId");

                    b.HasIndex("PredmetId");

                    b.ToTable("Delovi");
                });

            modelBuilder.Entity("AcademicManagmentSystem.API.Data.Katedra", b =>
                {
                    b.Property<int>("KatedraID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KatedraID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KatedraID");

                    b.ToTable("Katedre");
                });

            modelBuilder.Entity("AcademicManagmentSystem.API.Data.Predavac", b =>
                {
                    b.Property<int>("PredavacId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PredavacId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KatedraId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PredavacId");

                    b.HasIndex("KatedraId");

                    b.ToTable("Predavaci");
                });

            modelBuilder.Entity("AcademicManagmentSystem.API.Data.Predmet", b =>
                {
                    b.Property<int>("PredmetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PredmetId"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PredmetId");

                    b.ToTable("Predmeti");
                });

            modelBuilder.Entity("AcademicManagmentSystem.API.Data.PredmetPredavac", b =>
                {
                    b.Property<int>("PredmetId")
                        .HasColumnType("int");

                    b.Property<int>("PredavacId")
                        .HasColumnType("int");

                    b.HasKey("PredmetId", "PredavacId");

                    b.HasIndex("PredavacId");

                    b.ToTable("PredmetPredavaci");
                });

            modelBuilder.Entity("AcademicManagmentSystem.API.Data.Rezultat", b =>
                {
                    b.Property<int>("RezultatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RezultatId"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeoId")
                        .HasColumnType("int");

                    b.Property<int>("Ocena")
                        .HasColumnType("int");

                    b.Property<double>("Poeni")
                        .HasColumnType("float");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("RezultatId");

                    b.HasIndex("DeoId");

                    b.HasIndex("StudentId");

                    b.ToTable("Rezultati");
                });

            modelBuilder.Entity("AcademicManagmentSystem.API.Data.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Index")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Studenti");
                });

            modelBuilder.Entity("AcademicManagmentSystem.API.Data.Deo", b =>
                {
                    b.HasOne("AcademicManagmentSystem.API.Data.Predmet", "Predmet")
                        .WithMany("Delovi")
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predmet");
                });

            modelBuilder.Entity("AcademicManagmentSystem.API.Data.Predavac", b =>
                {
                    b.HasOne("AcademicManagmentSystem.API.Data.Katedra", "Katedra")
                        .WithMany("Predavaci")
                        .HasForeignKey("KatedraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Katedra");
                });

            modelBuilder.Entity("AcademicManagmentSystem.API.Data.PredmetPredavac", b =>
                {
                    b.HasOne("AcademicManagmentSystem.API.Data.Predavac", "Predavac")
                        .WithMany("PredmetPredavaci")
                        .HasForeignKey("PredavacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademicManagmentSystem.API.Data.Predmet", "Predmet")
                        .WithMany("PredmetPredavaci")
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predavac");

                    b.Navigation("Predmet");
                });

            modelBuilder.Entity("AcademicManagmentSystem.API.Data.Rezultat", b =>
                {
                    b.HasOne("AcademicManagmentSystem.API.Data.Deo", "Deo")
                        .WithMany("Rezultati")
                        .HasForeignKey("DeoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademicManagmentSystem.API.Data.Student", "Student")
                        .WithMany("Rezultati")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deo");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AcademicManagmentSystem.API.Data.Deo", b =>
                {
                    b.Navigation("Rezultati");
                });

            modelBuilder.Entity("AcademicManagmentSystem.API.Data.Katedra", b =>
                {
                    b.Navigation("Predavaci");
                });

            modelBuilder.Entity("AcademicManagmentSystem.API.Data.Predavac", b =>
                {
                    b.Navigation("PredmetPredavaci");
                });

            modelBuilder.Entity("AcademicManagmentSystem.API.Data.Predmet", b =>
                {
                    b.Navigation("Delovi");

                    b.Navigation("PredmetPredavaci");
                });

            modelBuilder.Entity("AcademicManagmentSystem.API.Data.Student", b =>
                {
                    b.Navigation("Rezultati");
                });
#pragma warning restore 612, 618
        }
    }
}
