// <auto-generated />
using AcademicManagmentSystem.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AcademicManagmentSystem.API.Migrations
{
    [DbContext(typeof(AcademicManagmentSystemDbContext))]
    [Migration("20240815211804_InitialMigrate")]
    partial class InitialMigrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AcademicManagmentSystem.API.Data.Deo", b =>
                {
                    b.Property<int>("DeoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeoId"));

                    b.Property<double>("BrojPoena")
                        .HasColumnType("float");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<double>("MaxBrPoena")
                        .HasColumnType("float");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Polozio")
                        .HasColumnType("bit");

                    b.Property<int>("PredmetId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TipId")
                        .HasColumnType("int");

                    b.HasKey("DeoId");

                    b.HasIndex("PredmetId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TipId");

                    b.ToTable("Delovi");
                });

            modelBuilder.Entity("AcademicManagmentSystem.API.Data.Katedra", b =>
                {
                    b.Property<int>("KatedraID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KatedraID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KatedraID");

                    b.ToTable("Katedre");

                    b.HasData(
                        new
                        {
                            KatedraID = 1,
                            Naziv = "Katedra 1"
                        },
                        new
                        {
                            KatedraID = 2,
                            Naziv = "Katedra 2"
                        },
                        new
                        {
                            KatedraID = 3,
                            Naziv = "Katedra 3"
                        });
                });

            modelBuilder.Entity("AcademicManagmentSystem.API.Data.Ocena", b =>
                {
                    b.Property<DateTime>("DatumPolaganja")
                        .HasColumnType("datetime2");

                    b.Property<int>("PredmetId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("VrednostOcene")
                        .HasColumnType("int");

                    b.HasKey("DatumPolaganja");

                    b.HasIndex("PredmetId");

                    b.HasIndex("StudentId");

                    b.ToTable("Ocene");
                });

            modelBuilder.Entity("AcademicManagmentSystem.API.Data.Predavac", b =>
                {
                    b.Property<int>("PredavacId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PredavacId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KatedraId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PredavacId");

                    b.HasIndex("KatedraId");

                    b.ToTable("Predavaci");

                    b.HasData(
                        new
                        {
                            PredavacId = 1,
                            Email = "petar.petrovic@example.com",
                            Ime = "Petar",
                            KatedraId = 1,
                            Password = "P@ssword_1",
                            Prezime = "Petrovic",
                            Username = "ppetrovic"
                        },
                        new
                        {
                            PredavacId = 2,
                            Email = "marko.markovic@example.com",
                            Ime = "Marko",
                            KatedraId = 2,
                            Password = "P@ssword_1",
                            Prezime = "Markovic",
                            Username = "mmarkovic"
                        },
                        new
                        {
                            PredavacId = 3,
                            Email = "zarko.zarkovic@example.com",
                            Ime = "Zarko",
                            KatedraId = 2,
                            Password = "P@ssword_1",
                            Prezime = "Zarkovic",
                            Username = "zzarkovic"
                        },
                        new
                        {
                            PredavacId = 4,
                            Email = "janko.jankovic@example.com",
                            Ime = "Janko",
                            KatedraId = 3,
                            Password = "P@ssword_1",
                            Prezime = "Jankovic",
                            Username = "jjankovic"
                        },
                        new
                        {
                            PredavacId = 5,
                            Email = "mirko.mirkovic@example.com",
                            Ime = "Mirko",
                            KatedraId = 1,
                            Password = "P@ssword_1",
                            Prezime = "Mirkovic",
                            Username = "mmirkovic"
                        });
                });

            modelBuilder.Entity("AcademicManagmentSystem.API.Data.Predmet", b =>
                {
                    b.Property<int>("PredmetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PredmetId"));

                    b.Property<int>("ESPB")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PredmetId");

                    b.ToTable("Predmeti");

                    b.HasData(
                        new
                        {
                            PredmetId = 1,
                            ESPB = 6,
                            Naziv = "Matematika 1",
                            Sifra = "MAT101"
                        },
                        new
                        {
                            PredmetId = 2,
                            ESPB = 8,
                            Naziv = "Osnove Programiranja",
                            Sifra = "INF101"
                        },
                        new
                        {
                            PredmetId = 3,
                            ESPB = 6,
                            Naziv = "Matematika 2",
                            Sifra = "MAT202"
                        },
                        new
                        {
                            PredmetId = 4,
                            ESPB = 5,
                            Naziv = "Osnove Organizacije",
                            Sifra = "ORG101"
                        });
                });

            modelBuilder.Entity("AcademicManagmentSystem.API.Data.PredmetPredavac", b =>
                {
                    b.Property<int>("PredmetId")
                        .HasColumnType("int");

                    b.Property<int>("PredavacId")
                        .HasColumnType("int");

                    b.HasKey("PredmetId", "PredavacId");

                    b.HasIndex("PredavacId");

                    b.ToTable("PredmetPredavaci");

                    b.HasData(
                        new
                        {
                            PredmetId = 2,
                            PredavacId = 1
                        },
                        new
                        {
                            PredmetId = 1,
                            PredavacId = 2
                        },
                        new
                        {
                            PredmetId = 3,
                            PredavacId = 2
                        },
                        new
                        {
                            PredmetId = 1,
                            PredavacId = 3
                        },
                        new
                        {
                            PredmetId = 4,
                            PredavacId = 4
                        },
                        new
                        {
                            PredmetId = 2,
                            PredavacId = 5
                        });
                });

            modelBuilder.Entity("AcademicManagmentSystem.API.Data.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Index")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Studenti");
                });

            modelBuilder.Entity("AcademicManagmentSystem.API.Data.Tip", b =>
                {
                    b.Property<int>("TipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipId"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipId");

                    b.ToTable("Tip");
                });

            modelBuilder.Entity("AcademicManagmentSystem.API.Data.Deo", b =>
                {
                    b.HasOne("AcademicManagmentSystem.API.Data.Predmet", "Predmet")
                        .WithMany("Delovi")
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademicManagmentSystem.API.Data.Student", "Student")
                        .WithMany("Delovi")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademicManagmentSystem.API.Data.Tip", "Tip")
                        .WithMany()
                        .HasForeignKey("TipId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Predmet");

                    b.Navigation("Student");

                    b.Navigation("Tip");
                });

            modelBuilder.Entity("AcademicManagmentSystem.API.Data.Ocena", b =>
                {
                    b.HasOne("AcademicManagmentSystem.API.Data.Predmet", "Predmet")
                        .WithMany("Ocene")
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademicManagmentSystem.API.Data.Student", "Student")
                        .WithMany("Ocene")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predmet");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AcademicManagmentSystem.API.Data.Predavac", b =>
                {
                    b.HasOne("AcademicManagmentSystem.API.Data.Katedra", "Katedra")
                        .WithMany("Predavaci")
                        .HasForeignKey("KatedraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Katedra");
                });

            modelBuilder.Entity("AcademicManagmentSystem.API.Data.PredmetPredavac", b =>
                {
                    b.HasOne("AcademicManagmentSystem.API.Data.Predavac", "Predavac")
                        .WithMany("PredmetPredavaci")
                        .HasForeignKey("PredavacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademicManagmentSystem.API.Data.Predmet", "Predmet")
                        .WithMany("PredmetPredavaci")
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predavac");

                    b.Navigation("Predmet");
                });

            modelBuilder.Entity("AcademicManagmentSystem.API.Data.Katedra", b =>
                {
                    b.Navigation("Predavaci");
                });

            modelBuilder.Entity("AcademicManagmentSystem.API.Data.Predavac", b =>
                {
                    b.Navigation("PredmetPredavaci");
                });

            modelBuilder.Entity("AcademicManagmentSystem.API.Data.Predmet", b =>
                {
                    b.Navigation("Delovi");

                    b.Navigation("Ocene");

                    b.Navigation("PredmetPredavaci");
                });

            modelBuilder.Entity("AcademicManagmentSystem.API.Data.Student", b =>
                {
                    b.Navigation("Delovi");

                    b.Navigation("Ocene");
                });
#pragma warning restore 612, 618
        }
    }
}
